language: node_js
env:
  - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
before_install:
  - npm install tsd -g
  - tsd install
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
sudo: false
after_success:
  - npm run coveralls